### ISSUE TITLE
double quotes are breaking syntax highlighting

### ISSUE THREAD

**Issue by smadep** [gncnpk/power-automate-expressions#1]
as highlighted in screen shot below a " breaks the syntax highlighting.
the middle argument of the concat loses its syntax highlighting.

`concat('//connector[id="',    item()?['apiId'],   '"]') `

![image](https://github.com/user-attachments/assets/ece04158-b02e-4991-ad30-466eca0f2712)

is it possible to also write comments?

otherwise a really great extension to make life easier, as long as syntax highlighting is not supported in flow editors. Thank you!

**Comment by gncnpk** [comment]
I'll take a look shortly!

**Comment by gncnpk** [comment]
Should be fixed in https://github.com/gncnpk/power-automate-expressions/commit/3de4429f17730e67a8465297d11c9fc1f4ddf30d

**Comment by smadep** [comment]
great! wait, it doesn't flag the parts red anymore, but now arguments at position greater than 1 e.g. below are highlighted like comments...

`concat('"', item()?['id'], '":', item())
`
or

`
union(outputs('var_arrConnections'),body('Simple_Map_Connections_With_Connector'))
`
or 

```
setProperty(
    item(), 
    'connector',
    json(
        coalesce(
            first(
            xpath(outputs('PrepXml')?['xml'], 
                  concat('//connector[id="', item()?['apiId'], '"]') 
            )
            )
        , '')
    )?['connector']
)

```
or

```
int(
    coalesce(
        first(xpath(outputs('ArrayConvertedToXml'),
                concat('//employee[email = "', variables('Email'), '"][1]/id/text()')
    ))
    ,'-1')
)
```

**Comment by smadep** [comment]
great - thanks! it's working!
